package com.seminarhub.dto;

public enum SettlementStrategy {
    READ_COMMITTED,
    READ_COMMITTED_PESSIMISTIC_WRITE,
    REPEATABLE_READ,
    REPEATABLE_READ_PESSIMISTIC_WRITE,
    SERIALIZABLE,
    SERIALIZABLE_PESSIMISTIC_WRITE
}
