plugins {
    id 'java'
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spring.dependency.management)
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.named('jar') {
    enabled = false
}

dependencies {
    compileOnly libs.lombok
    annotationProcessor libs.lombok

    implementation project(':common')
    implementation project(':data')
    implementation libs.bootStarterDataJpa
    implementation libs.bootStarterWeb
    implementation libs.bootStarterValidation
    implementation libs.springdocOpenapiStarterWebmvcUi
    implementation libs.springRetry

    runtimeOnly libs.postgresql

    testImplementation libs.bootStarterTest
    testRuntimeOnly libs.junitPlatformLauncher
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}
