plugins {
    id 'org.springframework.boot'
}

tasks.named('jar') {
    enabled = false
}

dependencies {
    implementation project(':common')
    implementation project(':data')
    implementation libs.bootStarterDataJpa
    implementation libs.bootStarterWeb
    implementation libs.bootStarterValidation
    implementation libs.springdocOpenapiStarterWebmvcUi
    implementation libs.springRetry
    implementation libs.bootStarterAspectj

    runtimeOnly libs.postgresql

    testImplementation libs.bootStarterTest
    testImplementation libs.bootStarterWebmvcTest
    testRuntimeOnly libs.junitPlatformLauncher
}
