plugins {
    id 'java'
    alias(libs.plugins.spring.dependency.management)
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

dependencyManagement {
    imports {
        mavenBom "${libs.springBootBom.get()}"
    }
}

dependencies {
    implementation project(':data')

    implementation libs.squirrelFoundation
}
