plugins {
    id 'java'
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spring.dependency.management)
}

bootJar { enabled = false }
jar { enabled = true }

java {
    toolchain { languageVersion = JavaLanguageVersion.of(21) }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    compileOnly libs.lombok
    annotationProcessor libs.lombok

    implementation "${libs.querydsl.jpa.get()}:jakarta"
    annotationProcessor(
            libs.jakarta.persistence.api,
            libs.jakarta.annotation.api,
            "${libs.querydsl.apt.get()}:jakarta"
    )
}

def generated = 'src/main/generated'
sourceSets {
    main.java.srcDirs += [ generated ]
}

tasks.withType(JavaCompile).configureEach {
    options.generatedSourceOutputDirectory = file(generated)
}

// Gradle 9.2 Configuration Cache 호환성을 위한 Clean Task 수정
tasks.named('clean', Delete) {
    delete file(generated)
}