apiVersion: apps/v1
kind: Deployment
metadata:
  name: seminarhub-member-seminar-api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      name: seminarhub-member-seminar-api-server
  template:
    metadata:
      labels:
        name: seminarhub-member-seminar-api-server
    spec:
      containers:
        - image: eoghdhdls/seminarhub-member-seminar-api-server
          name: seminarhub-member-seminar-api-server
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: seminarhub-member-seminar-api-server-dev
spec:
  ports:
    - port: 8082
      protocol: TCP
      name: "httpmemberseminar"
      targetPort: 8082
  selector:
    name: seminarhub-member-seminar-api-server
