apiVersion: apps/v1
kind: Deployment
metadata:
  name: seminarhub-cloud-gateway-server
spec:
  replicas: 1
  selector:
    matchLabels:
      name: seminarhub-cloud-gateway-server
  template:
    metadata:
      labels:
        name: seminarhub-cloud-gateway-server
    spec:
      containers:
        - image: eoghdhdls/seminarhub-cloud-gateway-server
          name: seminarhub-cloud-gateway-server
          ports:
            - containerPort: 80
      serviceAccountName: ingress-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: seminarhub-cloud-gateway-server-dev
spec:
  ports:
    - port: 80
      protocol: TCP
      name: "http"
      targetPort: 80
  selector:
    name: seminarhub-cloud-gateway-server
    #  serviceAccountName: ingress-nginx
