plugins {
    id 'java'
    id 'application'
    alias(libs.plugins.spring.dependency.management)
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = 'org.example2.Main'
}

dependencyManagement {
    imports {
        mavenBom "${libs.springBootBom.get()}"
    }
}

dependencies {
    implementation libs.springContext
    implementation libs.springContextSupport
    implementation libs.angusMail
    implementation libs.springJdbc
    implementation libs.h2
    testImplementation libs.junitJupiter
    testImplementation libs.mockitoCore
    testImplementation libs.springTest
    testRuntimeOnly libs.junitPlatformLauncher
}

tasks.named('test') {
    useJUnitPlatform()
    testLogging {
        showStandardStreams = true
    }
}
