plugins {
    id 'java'
    id 'application'
    alias(libs.plugins.spring.dependency.management)
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = 'org.example2.Main'
}

dependencyManagement {
    imports {
        mavenBom "${libs.springBootBom.get()}"
    }
}

dependencies {
    implementation libs.springContext
    implementation libs.springJdbc
    implementation 'com.h2database:h2:2.5.250'
}
