server:
  port: 8080

spring:
  application:
    name: seminarhub-settlement-server
  profiles:
    active: ${ACTIVE_PROFILE:local}

---
spring:
  config:
    activate:
      on-profile: ${ACTIVE_PROFILE:local}
    import: optional:file:.env[.properties], optional:file:../.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/seminar-hub}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.transaction.interceptor: TRACE
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG  