plugins {
    id 'java'
    alias(libs.plugins.spring.dependency.management)
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

dependencyManagement {
    imports {
        mavenBom "${libs.springBootBom.get()}"
    }
}

dependencies {
    compileOnly libs.lombok
    annotationProcessor libs.lombok

    implementation project(':common')
    implementation libs.bootStarterDataJpa
    implementation variantOf(libs.querydslJpa) {
        classifier('jakarta')
    }

    annotationProcessor variantOf(libs.querydslApt) {
        classifier('jakarta')
    }
    annotationProcessor libs.jakartaAnnotationApi
    annotationProcessor libs.jakartaPersistenceApi

    testImplementation libs.bootStarterTest
    testRuntimeOnly libs.junitPlatformLauncher
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}
