plugins {
    id 'java'
    alias(libs.plugins.spring.dependency.management)
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

dependencyManagement {
    imports {
        mavenBom "${libs.springBootBom.get()}"
    }
}

def generatedDir = layout.buildDirectory.dir('generated/querydsl')

sourceSets {
    main {
        java {
            srcDir generatedDir
        }
    }
}

tasks.named('compileJava', JavaCompile) {
    options.generatedSourceOutputDirectory.set(generatedDir)
}

dependencies {
    compileOnly libs.lombok
    annotationProcessor libs.lombok
    testCompileOnly libs.lombok
    testAnnotationProcessor libs.lombok

    implementation project(':common')
    implementation libs.bootStarterDataJpa
    implementation libs.springJdbc
    implementation variantOf(libs.querydslJpa) {
        classifier('jakarta')
    }

    annotationProcessor variantOf(libs.querydslApt) {
        classifier('jakarta')
    }
    annotationProcessor libs.jakartaAnnotationApi
    annotationProcessor libs.jakartaPersistenceApi

    testImplementation libs.bootStarterTest
    testRuntimeOnly libs.junitPlatformLauncher
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}
