plugins {
    id 'org.springframework.boot'
}

tasks.named('jar') {
    enabled = false
}

dependencies {
    implementation project(':common')
    implementation project(':data')
    implementation libs.bootStarterDataJpa
    implementation libs.bootStarterBatch
    implementation libs.springBatchIntegration
    implementation libs.bootStarterJdbc
    implementation libs.bootStarterWeb

    runtimeOnly libs.postgresql

    testImplementation libs.bootStarterTest
    testImplementation libs.bootStarterWebmvcTest
    testImplementation libs.springBatchTest
    testRuntimeOnly libs.h2
    testRuntimeOnly libs.junitPlatformLauncher
}
