plugins {
    id 'java'
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spring.dependency.management)
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.named('jar') {
    enabled = false
}

dependencies {
    compileOnly libs.lombok
    annotationProcessor libs.lombok
    testCompileOnly libs.lombok
    testAnnotationProcessor libs.lombok

    implementation project(':common')
    implementation project(':data')
    implementation libs.bootStarterDataJpa
    implementation libs.bootStarterBatch
    implementation libs.springBatchIntegration
    implementation libs.bootStarterWeb

    runtimeOnly libs.postgresql

    testImplementation libs.bootStarterTest
    testImplementation libs.bootStarterWebmvcTest
    testRuntimeOnly libs.junitPlatformLauncher
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}
